const data = [
  {
    image: "Image",
    item_code: "ITEM CODE",
    item_name: "ITEM NAME",
    item_category: "ITEM CATEGORY",
    current_stock: "CURRENT STOCK",
    item_price: "ITEM PRICE (Rs.)",
    selling_price: "SELLING PRICE (Price/Unit)",
    minimum_stock: "MINIMUM STOCK",
    expiry: "EXPIRY",
    status: "STATUS",
  },
  {
    image: "Image1",
    item_code: "WS0005",
    item_name: "PANNER",
    item_category: "WHITE",
    current_stock: "90 kg",
    item_price: "3916.83",
    selling_price: "32.00/kg",
    minimum_stock: "200 kgs",
    expiry: "15/03/2023",
    status: "ACTIVE",
  },
  {
    image: "Image2",
    item_code: "CTF001",
    item_name: "CATTLE FEED 1",
    item_category: "CATTLE FEED",
    current_stock: "12 kg",
    item_price: "712.56",
    selling_price: "12.13/KG",
    minimum_stock: "50 kgs",
    expiry: "NO EXPIRY",
    status: "ACTIVE",
  },
  {
    image: "Image3",
    item_code: "AS08893 ",
    item_name: "LPG CYLINDER",
    item_category: "ASSET",
    current_stock: "7 pcs",
    item_price: "5019.74",
    selling_price: "18.46/kg",
    minimum_stock: "4 pcs",
    expiry: "NO EXPIRY",
    status: "ACTIVE",
  },
  {
    image: "Image4",
    item_code: "WS0005",
    item_name: "CARROT",
    item_category: "GREEN",
    current_stock: "20 kg",
    item_price: "1896.40",
    selling_price: "15.11/kg",
    minimum_stock: "200 kgs",
    expiry: "15/03/2023",
    status: "ACTIVE",
  },
  {
    image: "Image5",
    item_code: "GS00052 ",
    item_name: "BASMATI RIC",
    item_category: "BROWN",
    current_stock: "400 kg",
    item_price: "15228.09",
    selling_price: "32.00/kg",
    minimum_stock: "50 kgs",
    expiry: "NO EXPIRY",
    status: "ACTIVE",
  },
  {
    image: "Image6",
    item_code: "BS56123 ",
    item_name: "PANNER",
    item_category: "WHITE",
    current_stock: "90 kg",
    item_price: "3916.83",
    selling_price: "12.13/kg",
    minimum_stock: "4 pcs",
    expiry: "NO EXPIRY",
    status: "ACTIVE",
  },
  {
    image: "Image7",
    item_code: "WS0005",
    item_name: "CATTLE FEED 1",
    item_category: "CATTLE FEED",
    current_stock: "12 kg",
    item_price: "712.5",
    selling_price: "18.46/kg",
    minimum_stock: "50 kgs",
    expiry: "NO EXPIRY",
    status: "ACTIVE",
  },
  {
    image: "Image7",
    item_code: "WS0005",
    item_name: "CATTLE FEED 1",
    item_category: "CATTLE FEED",
    current_stock: "12 kg",
    item_price: "712.56",
    selling_price: "18.46/kg",
    minimum_stock: "4 pcs",
    expiry: "NO EXPIRY",
    status: "ACTIVE",
  },
];
